# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-11-27 11:45
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('search', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mobile',
            name='info',
            field=models.CharField(max_length=10000),
        ),
        migrations.AlterField(
            model_name='mobile',
            name='price',
            field=models.DecimalField(decimal_places=2, max_digits=5),
        ),
        migrations.AlterField(
            model_name='mobile',
            name='url',
            field=models.CharField(max_length=1000),
        ),
    ]
