# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-11-27 12:00
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('search', '0002_auto_20161127_1715'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mobile',
            name='avalable',
            field=models.TextField(max_length=500),
        ),
        migrations.AlterField(
            model_name='mobile',
            name='info',
            field=models.TextField(max_length=10000),
        ),
        migrations.AlterField(
            model_name='mobile',
            name='price',
            field=models.DecimalField(decimal_places=2, max_digits=10),
        ),
        migrations.AlterField(
            model_name='mobile',
            name='title',
            field=models.TextField(max_length=800),
        ),
        migrations.AlterField(
            model_name='mobile',
            name='url',
            field=models.TextField(max_length=10000),
        ),
    ]
